# Generated by Django 3.1 on 2021-12-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_auto_20211208_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descriptioin', models.TextField(blank=True, max_length=500)),
                ('price', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('location', models.CharField(max_length=200, unique=True)),
                ('expire_date', models.DateTimeField(blank=True)),
                ('package_form', models.CharField(max_length=200, unique=True)),
                ('images', models.ImageField(upload_to='photos/products')),
                ('stocks', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
