# Generated by Django 3.1 on 2021-12-08 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211208_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expire_date',
        ),
    ]
